### ISSUE TITLE
[Feat] fonted-card

### ISSUE THREAD

**Issue by HongYongGuen** [HyeonjinChoi/TaskFlow#43]
## 기능 설명

- 프론트 카드 생성/ 삭제/ 무브 부분 구현

## 작업 상세 내용

- [ ] 카드 생성
- [ ] 카드 삭제
- [ ] 카드 무브

**Comment by HyeonjinChoi** [comment]
기능 설명에는 프론트엔트 카드에 대한 구현이라고 되어있는데
실제로는 회원가입에 대한 구현을 하신 건가요?
